# Generated by Django 5.2.15 on 2026-06-13 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jenjang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(max_length=100)),
                ('nomor_rekening', models.CharField(max_length=50)),
                ('atas_nama', models.CharField(max_length=150)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rekening',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('file_jadwal', models.FileField(upload_to='jadwal/')),
                ('aktif', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='les.jenjang')),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
                'ordering': ['judul'],
            },
        ),
        migrations.CreateModel(
            name='PaketLes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=150)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_les', to='les.jenjang')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_les', to='les.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Paket Les',
                'ordering': ['nama_paket'],
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pendaftaran', models.CharField(max_length=30, unique=True)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MENUNGGU_PEMBAYARAN', 'Menunggu Pembayaran'), ('MENUNGGU_VERIFIKASI', 'Menunggu Verifikasi'), ('AKTIF', 'Aktif'), ('DITOLAK', 'Ditolak'), ('SELESAI', 'Selesai')], default='MENUNGGU_PEMBAYARAN', max_length=30)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='les.paketles')),
            ],
            options={
                'verbose_name_plural': 'Pendaftaran',
                'ordering': ['-tanggal_daftar'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nama_pengirim', models.CharField(max_length=150)),
                ('bank_pengirim', models.CharField(max_length=100)),
                ('bukti_transfer', models.ImageField(upload_to='bukti_transfer/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='les.pendaftaran')),
            ],
            options={
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('sekolah', models.CharField(max_length=150)),
                ('kelas_sekolah', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('no_hp_ortu', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='siswa/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Siswa',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='les.siswa'),
        ),
    ]
